"""Wordlists for semantic ID generation.

Three curated wordlists of 400 neutral, descriptive words each.
These words are selected to be:
- Easy to pronounce and remember
- Culturally neutral
- Distinct from each other to minimize confusion
"""

# List 1: Technology, Science & Greek Letters (400 words)
TECH_SCIENCE_WORDS = [
    "alpha", "beta", "gamma", "delta", "epsilon", "zeta", "eta", "theta",
    "iota", "kappa", "lambda", "mu", "nu", "xi", "omicron", "pi",
    "rho", "sigma", "tau", "upsilon", "phi", "chi", "psi", "omega",
    "atom", "ion", "proton", "neutron", "electron", "photon", "quark", "boson",
    "carbon", "hydrogen", "oxygen", "nitrogen", "helium", "neon", "argon", "xenon",
    "sodium", "potassium", "calcium", "iron", "copper", "silver", "gold", "zinc",
    "silicon", "titanium", "platinum", "lithium", "magnesium", "aluminum", "nickel", "cobalt",
    "byte", "pixel", "vector", "matrix", "array", "buffer", "cache", "codec",
    "cipher", "token", "packet", "socket", "portal", "gateway", "bridge", "router",
    "server", "client", "proxy", "daemon", "kernel", "shell", "module", "plugin",
    "widget", "gadget", "device", "sensor", "beacon", "scanner", "tracker", "monitor",
    "arc", "axis", "chord", "curve", "edge", "face", "graph", "grid",
    "helix", "line", "loop", "mesh", "node", "orbit", "path", "plane",
    "point", "radius", "ray", "scale", "sphere", "spiral", "surface", "tangent",
    "vertex", "volume", "wave", "zone", "angle", "circle", "cone", "cylinder",
    "logic", "syntax", "parser", "lexer", "compiler", "linker", "loader", "debugger",
    "thread", "process", "queue", "stack", "heap", "frame", "scope", "context",
    "state", "event", "signal", "trigger", "handler", "listener", "observer", "reactor",
    "stream", "flow", "pipe", "filter", "mapper", "reducer", "wrapper", "adapter",
    "block", "chunk", "shard", "segment", "fragment", "slice", "batch", "bucket",
    "index", "key", "hash", "digest", "checksum", "signature", "seal", "stamp",
    "record", "entry", "field", "column", "row", "table", "schema", "catalog",
    "archive", "vault", "depot", "store", "pool", "bank", "ledger", "file",
    "link", "channel", "wire", "cable", "fiber", "band", "carrier", "hub",
    "switch", "peer", "host", "guest", "endpoint", "interface", "protocol", "format",
    "codec", "header", "payload", "footer", "trailer", "envelope", "container", "package",
    "pattern", "template", "blueprint", "model", "draft", "sketch", "outline", "structure",
    "framework", "scaffold", "skeleton", "spine", "core", "nucleus", "center", "layer",
    "level", "tier", "stage", "phase", "step", "cycle", "round", "branch",
    "fork", "merge", "split", "join", "union", "cross", "scan", "parse",
    "compile", "build", "fetch", "read", "write", "copy", "move", "swap",
    "shift", "rotate", "flip", "push", "pull", "send", "receive", "emit",
    "listen", "watch", "track", "lock", "unlock", "verify", "check", "test",
    "bit", "nibble", "word", "dword", "qword", "page", "sector", "unit",
    "metric", "gauge", "meter", "ruler", "measure", "counter", "rate", "speed",
    "pace", "tempo", "rhythm", "beat", "pulse", "tick", "span", "range",
    "scope", "extent", "reach", "limit", "bound", "margin", "concept", "idea",
    "notion", "theme", "motif", "aspect", "facet", "trait", "feature", "quality",
    "property", "attribute", "domain", "realm", "mode", "status", "type", "kind",
    "class", "group", "set", "collection", "series", "sequence", "engine", "motor",
    "pump", "valve", "relay", "circuit", "board", "chip", "element", "part",
    "piece", "gear", "lever", "spring", "coil", "magnet", "conduit", "plate",
    "panel", "screen", "display", "indicator", "light", "lamp", "bulb", "power",
    "energy", "force", "charge", "voltage", "current", "watt", "amp", "volt",
    "ohm", "hertz", "joule", "newton", "pascal", "tesla", "weber", "flux",
    "beam", "spark", "flash", "surge", "spike", "boost", "gain", "loss",
    "drain", "leak", "waste", "space", "void", "gap", "slot", "hole",
    "port", "gate", "door", "window", "border", "corner", "side", "wall",
    "floor", "ceiling", "roof", "base", "top", "bottom", "front", "back",
    "left", "right", "north", "south", "east", "west", "middle", "time",
]

# List 2: Nature, Elements & Geography (400 words)
NATURE_ELEMENTS_WORDS = [
    "solar", "lunar", "stellar", "comet", "meteor", "asteroid", "nebula", "galaxy",
    "star", "sun", "moon", "planet", "earth", "mars", "venus", "jupiter",
    "saturn", "mercury", "neptune", "uranus", "pluto", "titan", "europa", "io",
    "cosmos", "orbit", "eclipse", "zenith", "nadir", "apex", "wind", "breeze",
    "gale", "storm", "tempest", "cyclone", "typhoon", "monsoon", "rain", "drizzle",
    "shower", "deluge", "torrent", "mist", "fog", "haze", "cloud", "cirrus",
    "cumulus", "nimbus", "stratus", "vapor", "steam", "dew", "frost", "ice",
    "snow", "sleet", "hail", "crystal", "flake", "blizzard", "ocean", "sea",
    "gulf", "bay", "cove", "inlet", "strait", "channel", "river", "stream",
    "brook", "creek", "rapids", "falls", "cascade", "delta", "lake", "pond",
    "pool", "lagoon", "marsh", "swamp", "bog", "fen", "spring", "fountain",
    "geyser", "well", "source", "basin", "reservoir", "estuary", "mountain", "peak",
    "summit", "ridge", "crest", "pinnacle", "spire", "dome", "valley", "canyon",
    "gorge", "ravine", "gulch", "gully", "chasm", "abyss", "hill", "knoll",
    "mound", "rise", "slope", "incline", "grade", "ramp", "plain", "plateau",
    "mesa", "butte", "cliff", "bluff", "escarpment", "precipice", "rock", "stone",
    "boulder", "pebble", "gravel", "sand", "silt", "clay", "granite", "marble",
    "slate", "basalt", "quartz", "limestone", "sandstone", "shale", "mineral", "ore",
    "gem", "diamond", "ruby", "emerald", "sapphire", "lava", "magma", "ash",
    "pumice", "obsidian", "flint", "chalk", "gypsum", "forest", "woodland", "grove",
    "copse", "thicket", "brush", "bush", "shrub", "tree", "oak", "pine",
    "maple", "birch", "willow", "cedar", "cypress", "palm", "bamboo", "fern",
    "moss", "lichen", "algae", "kelp", "seaweed", "grass", "lawn", "meadow",
    "field", "prairie", "steppe", "savanna", "tundra", "cave", "cavern", "grotto",
    "den", "hollow", "burrow", "tunnel", "passage", "arch", "natural", "formation",
    "tower", "pillar", "column", "reef", "coral", "atoll", "shoal", "sandbar",
    "spit", "barrier", "island", "shore", "coast", "beach", "strand", "dune",
    "bank", "spring", "summer", "autumn", "winter", "season", "solstice", "equinox",
    "dawn", "morning", "noon", "evening", "dusk", "twilight", "night", "midnight",
    "sunrise", "sunset", "daybreak", "nightfall", "aurora", "meridian", "horizon", "skyline",
    "tide", "ebb", "shadow", "shade", "gleam", "glow", "shimmer", "glimmer",
    "sparkle", "reflection", "refraction", "prism", "spectrum", "rainbow", "halo", "corona",
    "aura", "thunder", "lightning", "bolt", "strike", "flare", "blaze", "borealis",
    "australis", "radiance", "luminance", "brilliance", "amber", "azure", "cobalt", "crimson",
    "jade", "coral", "pearl", "ivory", "ebony", "bronze", "slate", "charcoal",
    "smoke", "terra", "ochre", "umber", "sienna", "russet", "tawny", "desert",
    "oasis", "waste", "barren", "arid", "dry", "jungle", "rainforest", "canopy",
    "undergrowth", "verdant", "lush", "dense", "thick", "arctic", "polar", "frozen",
    "glacial", "permafrost", "icepack", "tropical", "equatorial", "humid", "sultry", "warm",
    "hot", "balmy", "mild", "habitat", "biome", "ecosystem", "environment", "niche",
    "territory", "wetland", "marshland", "bayou", "mangrove", "floodplain", "grassland", "pampas",
    "veldt", "taiga", "boreal", "temperate", "deciduous", "coniferous", "wood", "timber",
    "lumber", "bark", "branch", "twig", "leaf", "needle", "fiber", "cotton",
    "linen", "hemp", "jute", "silk", "wool", "leather", "shell", "bone",
    "horn", "resin", "oil", "wax", "tar", "pitch", "sap", "latex",
    "gum", "erosion", "weathering", "sediment", "deposit", "strata", "bed", "vein",
    "fault", "fold", "rift", "crack", "fissure", "crevice", "break", "terrace",
    "bench", "shelf", "platform", "ledge", "fan", "vale", "dell", "glen",
    "meadows", "clearing", "vista", "outlook", "view", "scene", "landscape", "seascape",
    "cloudscape", "rockface", "waterfall", "rapids", "whitewater", "eddy", "current", "undertow",
]

# List 3: Abstract, Geometry & Numbers (400 words)
GEOMETRY_ABSTRACT_WORDS = [
    "zero", "one", "two", "three", "four", "five", "six", "seven",
    "eight", "nine", "ten", "dozen", "score", "hundred", "thousand", "million",
    "single", "double", "triple", "quad", "quint", "hex", "sept", "octo",
    "first", "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth",
    "prime", "even", "odd", "whole", "half", "quarter", "tenth", "square",
    "triangle", "rectangle", "pentagon", "hexagon", "heptagon", "octagon", "cube", "torus",
    "oval", "ellipse", "parabola", "hyperbola", "whorl", "vortex", "polygon", "polyhedron",
    "tetrahedron", "dodecahedron", "icosahedron", "rhombus", "trapezoid", "parallelogram", "dimension", "coordinate",
    "scalar", "tensor", "horizontal", "vertical", "diagonal", "parallel", "perpendicular", "normal",
    "radial", "lateral", "medial", "proximal", "distal", "anterior", "posterior", "superior",
    "inferior", "inward", "outward", "upward", "downward", "forward", "backward", "sideways",
    "crossways", "micro", "mini", "small", "medium", "large", "mega", "giant",
    "jumbo", "tiny", "petite", "compact", "modest", "ample", "spacious", "vast",
    "immense", "short", "long", "narrow", "wide", "thin", "thick", "slim",
    "broad", "shallow", "deep", "low", "high", "tall", "brief", "extended",
    "red", "orange", "yellow", "green", "blue", "indigo", "violet", "purple",
    "cyan", "magenta", "lime", "teal", "navy", "maroon", "olive", "aqua",
    "white", "black", "gray", "grey", "beige", "tan", "pink", "rose",
    "peach", "cream", "mint", "sage", "plum", "wine", "stripe", "band",
    "bar", "dash", "dot", "spot", "speck", "checker", "lattice", "weave",
    "braid", "plait", "twist", "ripple", "zigzag", "chevron", "herringbone", "argyle",
    "plaid", "curl", "ring", "smooth", "rough", "coarse", "fine", "soft",
    "hard", "firm", "tender", "glossy", "matte", "shiny", "dull", "bright",
    "dim", "vivid", "pale", "sharp", "blunt", "keen", "obtuse", "acute",
    "precise", "vague", "fuzzy", "crisp", "blur", "clear", "hazy", "distinct",
    "faint", "bold", "subtle", "above", "below", "over", "under", "inside",
    "outside", "within", "beyond", "near", "far", "close", "distant", "adjacent",
    "remote", "between", "among", "amid", "through", "across", "along", "around",
    "about", "before", "after", "during", "throughout", "until", "since", "from",
    "toward", "simple", "complex", "plain", "fancy", "basic", "advanced", "pure",
    "mixed", "partial", "complete", "incomplete", "full", "empty", "solid", "hollow",
    "sparse", "heavy", "quick", "gradual", "sudden", "steady", "stable", "fluid",
    "equal", "unequal", "same", "different", "similar", "distinct", "alike", "unlike",
    "intersect", "diverge", "converge", "meet", "overlap", "separate", "connect", "combine",
    "match", "pair", "couple", "twin", "dual", "mutual", "reciprocal", "inverse",
    "start", "begin", "initial", "genesis", "origin", "median", "mean", "average",
    "mid", "midst", "final", "last", "ultimate", "terminal", "finish", "next",
    "previous", "prior", "subsequent", "following", "preceding", "successive", "serial", "change",
    "spin", "revolve", "reverse", "invert", "mirror", "reflect", "transpose", "exchange",
    "grow", "shrink", "expand", "contract", "stretch", "compress", "inflate", "deflate",
    "blend", "mix", "fuse", "isolate", "extract", "and", "or", "not",
    "xor", "nor", "nand", "implies", "equiv", "all", "any", "some",
    "none", "every", "each", "both", "either", "plus", "minus", "times",
    "divide", "modulo", "root", "log", "sum", "product", "quotient", "remainder",
    "factor", "multiple", "divisor", "dividend", "subset", "superset", "intersection", "difference",
    "complement", "member", "belong", "contain", "include", "exclude", "null", "universal",
    "total", "finite", "infinite", "countable", "continuous", "discrete", "image", "preimage",
    "mapping", "function", "relation", "open", "closed", "compact", "connected", "chain",
    "boundary", "interior", "exterior", "frontier", "neighbor", "incident", "degree", "order",
    "rank", "depth", "height", "network", "web", "graph", "tree", "forest",
]

# Verify word counts
assert len(TECH_SCIENCE_WORDS) == 400, f"TECH_SCIENCE_WORDS has {len(TECH_SCIENCE_WORDS)} words, expected 400"
assert len(NATURE_ELEMENTS_WORDS) == 400, f"NATURE_ELEMENTS_WORDS has {len(NATURE_ELEMENTS_WORDS)} words, expected 400"
assert len(GEOMETRY_ABSTRACT_WORDS) == 400, f"GEOMETRY_ABSTRACT_WORDS has {len(GEOMETRY_ABSTRACT_WORDS)} words, expected 400"

# All wordlists
ALL_WORDLISTS = [
    TECH_SCIENCE_WORDS,
    NATURE_ELEMENTS_WORDS,
    GEOMETRY_ABSTRACT_WORDS,
]
